### ISSUE TITLE
espresso-contrib 3.4.0 causing jdk11 sources to be included in release aab build

### ISSUE THREAD

**Issue by tfrysinger** [android/android-test#1007]
I create a release, signed aab build using the latest set of espresso and junit implementations (the implementation line is needed because I use the CountingIdlingResourceSingleton mechanism within my splash screen launching activity to increment the count and in the MainActivity which is started by the splash screen to decrement the count).

This release is ~7MB larger than the previous release. Upon investigation I see that 

### Steps to Reproduce
Create a full build referencing the 3.4.0 version of espresso-contrib, i.e. 

implementation 'androidx.test.espresso:espresso-contrib:3.4.0'

INSTEAD OF USING:

implementation 'androidx.test.espresso:espresso-contrib:3.3.0'

### Expected Results
My signed apk does not include jdk11 source folder.

### Actual Results
My signed apk includes the jdk11 source folder

### AndroidX Test and Android OS Versions
targeting android 30, using androidx esspresso-config 3.4.0

### Link to a public git repo demonstrating the problem:
[Here](https://stackoverflow.com/questions/68340598/why-does-creating-a-release-build-include-jdk-11-source) is a link to a StackOverflow entry further describing the problem with a couple of screenshots.

**Comment by ralf-at-android** [comment]
Thank you for bringing this to our attention. For the record, and in case others find this later: an external contributor found this was due to pulling external transient dependency org.checkerframework:checker:3.1.1. 
Please update to androidx.test.espresso:espresso-contrib:3.5.0-alpha05 released on 03/21/2022.
