### ISSUE TITLE
I have setup the java_home path and still I am getting this below error. 

### ISSUE THREAD

**Issue by NikitaTurakhia** [android/android-test#1372]
![image](https://user-images.githubusercontent.com/21182650/171192513-53d10e25-eb44-4c3d-829e-9869660aca41.png)
![image](https://user-images.githubusercontent.com/21182650/171192667-0e0b9146-d3fb-4403-8547-d22756086524.png)

![image](https://user-images.githubusercontent.com/21182650/171192733-bcb6f59d-207e-471d-ab41-0fe2346dda4f.png)

Does anyone has any idea why am I getting this error?

**Comment by NikitaTurakhia** [comment]
@utzcoz Do you know what it should be? and if it is selenium issue then why it shows java path error to me?

**Comment by utzcoz** [comment]
@NikitaTurakhia You can check https://javatutorial.net/set-java-home-windows-10/ step by step if you think your Java environment is not correctly. Maybe you need to close this issue, because it is not related to this project.

**Comment by adazh** [comment]
Not related to androidx test libraries.
