### ISSUE TITLE
GrantPermissionRule not working for sub-module's androidTest when grant new storage permission on android 13

### ISSUE THREAD

**Issue by eahom1** [android/android-test#1510]
### Description
I have android test cases on both app module & sub-module. Before upgrading to android API 33, the test cases used `READ_EXTERNAL_STORAGE` by `GrantPermissionRule`, and after upgrade to android API 33, the permission is changed, I have used `READ_MEDIA_IMAGE` instead. But when I run androidTest, the `GrantPermissionRule.grant(READ_MEDIA_IMAGE)` on app module works properly, but the same method on sub-module NOT working! And I have tried to upgrade the `androidx.test.rules` library to [1.4.1-alpha07](https://developer.android.com/jetpack/androidx/releases/test) it's still NOT working!
It throws the exception. Please refer to the screenshot.
![image](https://user-images.githubusercontent.com/11750409/190941447-c60c2a76-14dc-4651-876b-2eaa0d50f164.png)

BTW, other previous permission in sub-module's androidTest is still working by GrantPermissionRule on android-13, only the new permissions is NOT working.

### Steps to Reproduce
1. create an android test case with `GrantPermissionRule.grant(READ_MEDIA_IMAGE)` in any sub-module 
2. run it.

### Expected Results
test case should run passed

### Actual Results
throw exception

### AndroidX Test and Android OS Versions
issue happened on the following versions:
androidx.test.core: 1.4.0, 1.5.0-alpha02
androidx.test.rules: 1.4.0, 1.4.1-alpha07
espresso: 3.3.0-rc01, 3.5.0-alpha07
API version: 33

**Comment by TWiStErRob** [comment]
@eahom1 is it something anyone finding this issue could also apply?

**Comment by vinaypotluri** [comment]
@eahom1 Doesn't adding permissions within AndroidManifest.xml apply to all test suites ?
GrantPermissionRule should grant runtime permission within a single test suite
