### ISSUE TITLE
Espresso: AdapterView.getItemCount() returns only count of visisble Items instead of count of all items

### ISSUE THREAD

**Issue by jongerrish** [android/android-test#233]
See: https://issuetracker.google.com/124315578

After Updating Android Studio to 3.3.1 (also updated all other things which was susggested by Android Studio) some Espresso tests fail. Before the update they run.
I figured out, that all tests which uses my custum matcher for item count in AdapterView fail. I played around a little bit and see that AdapterView.getItemCount() always returns <8>. This is, i think, the number of visible items. Before the update this worked and the real itemCount was returned.

**Comment by adazh** [comment]
Closing this issue due to lack of information on the custom matcher. Please re-open if this is still an issue or more information/repro steps can be provided.
