### ISSUE TITLE
build fail: ERROR: error loading package '': Encountered error while reading extension file 'gmaven.bzl': no such package '@gmaven_rules//': java.io.IOException:

### ISSUE THREAD

**Issue by yuzhidi** [android/android-test#241]
### Link to a public git repo demonstrating the problem:

$ bazel build :axt_m2repository
INFO: SHA256 (https://github.com/aj-michael/gmaven_rules/archive/a5bc4640c35dd9b8234731678e9953f9fa64e0eb.tar.gz) = 1eebfed74c1a5f78529984ce4a47fc9a9139a7a07ec34f3db99bae3460cdada2
ERROR: error loading package '': Encountered error while reading extension file 'gmaven.bzl': no such package '@gmaven_rules//': java.io.IOException: Prefix gmaven_rules-a5bc4640c35dd9b8234731678e9953f9fa64e0eb was given, but not found in the archive
ERROR: error loading package '': Encountered error while reading extension file 'gmaven.bzl': no such package '@gmaven_rules//': java.io.IOException: Prefix gmaven_rules-a5bc4640c35dd9b8234731678e9953f9fa64e0eb was given, but not found in the archive
INFO: Elapsed time: 4.890s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by jin** [comment]
Sorry for the breakages. Please temporarily add this snippet to the WORKSPACE file as a workaround: 

```
RULES_JVM_EXTERNAL_TAG = "1.0"
http_archive(
    name = "gmaven_rules",
    strip_prefix = "rules_jvm_external-%s" % RULES_JVM_EXTERNAL_TAG,
    sha256 = RULES_JVM_EXTERNAL_SHA,
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/%s.zip" % RULES_JVM_EXTERNAL_TAG,
)
```

**Comment by jin** [comment]
The fix is 
https://github.com/android/android-test/pull/240

Cc @brettchabot @slinzner

**Comment by jin** [comment]
https://github.com/android/android-test/commit/5e9e63951c109eaca3a11c927261ab16b779bc0a should fix this.
