### ISSUE TITLE
Set up the framework in Espresso to support Flutter testing

### ISSUE THREAD

**Issue by adazh** [android/android-test#249]

**Comment by adazh** [comment]
Started working on assertions.

**Comment by xster** [comment]
Are there docs for how to do this and make assertions on Flutter UI via espresso?

**Comment by adazh** [comment]
Not yet. We are actively working on it. Stay tuned :).

**Comment by DhonyImamS** [comment]
hi @adazh , so it means that as if we had flutter app, it is better to run using flutter driver UI test rather than Espresso ?

**Comment by adazh** [comment]
@DhonyImamS Hi, it depends on your testing scenario.
Espresso would be most useful if your tests need to cover both Android views and Flutter views, or native plugin is involved. A bonus point is that Espresso will provide similar synchronization support for Flutter, and we are currently working on that (see https://github.com/flutter/flutter/issues/37409).

**Comment by DhonyImamS** [comment]
Hi @adazh, thanks for your reply, for now on will I Stay tuned till the espresso 100% can test UI flutter or is it possible for me to try espresso testing Flutter UI just for normal and standard interaction? If yes, i will start to integrate my repository flutter with espresso

**Comment by adazh** [comment]
@DhonyImamS, Thanks for your interest!

It's not ready yet. Please stay tuned! We will keep you posted once it's good for a try!

**Comment by Mohit020888** [comment]
@adazh - Hi , are there any updates on espresso support for flutter ? 
Thanks !

**Comment by atulbothe** [comment]
Is there any update on this? Or is there any other tool that can be used for Flutter UI testing especially without writing code (Record/Playback kind of features)

**Comment by almaz010891** [comment]
> Is there any update on this? Or is there any other tool that can be used for Flutter UI testing especially without writing code (Record/Playback kind of features)

same question
