### ISSUE TITLE
[Espresso] CLEARTEXT communication to 127.0.0.1 not permitted on 28+

### ISSUE THREAD

**Issue by adazh** [android/android-test#333]
When sending requests to Flutter app's Dart VM service extension, hitting the CLEARTEXT error on 28:
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: shortMsg: java.net.UnknownServiceException
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: longMsg: java.net.UnknownServiceException: CLEARTEXT communication to 127.0.0.1 not permitted by network security policy
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: timeMillis: 1557173593460
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: stackTrace:
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: java.lang.RuntimeException: WebSocket request failure.
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at androidx.test.espresso.flutter.internal.jsonrpc.JsonRpcClient$WebSocketListenerImpl.onFailure(JsonRpcClient.java:151)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:546)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.ws.RealWebSocket$2.onFailure(RealWebSocket.java:211)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:161)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at java.lang.Thread.run(Thread.java:764)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: Caused by: java.net.UnknownServiceException: CLEARTEXT communication to 127.0.0.1 not permitted by network security policy
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:144)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
05-06 13:13:13.460  1840  1903 E ActivityControllerCore: 	... 4 more

**Comment by mosofsky** [comment]
FYI I got this error while trying to implement integration tests for Flutter running on an Android device.  The solution was to add the following line to android/app/src/debug/AndroidManifest.xml:

```
<application android:usesCleartextTraffic="true"/>
```

This solution is also mentioned at https://stackoverflow.com/a/55604762/2848676 .

I remember reading that I needed to add that in one of the Flutter instructions but then when I reimplemented everything to work around another issue, I forgot to add this line back to the AndroidManifest.xml.
