### ISSUE TITLE
Python 2 targets must be annotated as `python_version = "PY2"`

### ISSUE THREAD

**Issue by brandjon** [android/android-test#373]
The breakage at googlesamples/android-testing#266 can be traced back to a [target](https://github.com/android/android-test/blob/3597c5c92b191f09935fe6a144254284075a38a9/tools/android/emulator/BUILD.bazel#L121-L135) in this repo that has a Python 2 main file (old `print` syntax) but uses the default `python_version` of `PY3`. This causes breakages when Bazel is [fixed](bazelbuild/bazel#7899) to (correctly) use the version of Python specified by the build, rather than whatever the system `python` version is.

The change exposing this breakage will happen in Bazel 0.27.

**Comment by jin** [comment]
Unfortunately unified_launcher runs in the host configuration, so every user of unified launcher will now need to specify --host_force_python=PY2.
