### ISSUE TITLE
Capture Google Play Protect selection

### ISSUE THREAD

**Issue by phileo** [android/android-test#395]
### Description
Currently, The Espresso Test Recorder is able to capture the user's selection in the Real time Permissions Dialog (Deny / Allow)

It would highly desirable for the Espresso Test Recorder to be able to capture the user's selection in the Google Play Protect Dialog In the same manner as the Real-Time permissions dialog

**Comment by parekhkishan611** [comment]
Please re-open this issue in the Espresso Test Recorder component.
