### ISSUE TITLE
ApplicationProvider.getApplicationContext() doesn't work in local unit test

### ISSUE THREAD

**Issue by yongce** [android/android-test#409]
### Description

From the demo at https://developer.android.com/training/testing/unit-testing/local-unit-tests#include-framework-dependencies, we should be able to use ApplicationProvider.getApplicationContext() in local unit test. Also, Robolectric suggests to use it too. But when I invoke it in local unit test, the exception "java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation." was thrown.

### Steps to Reproduce
Invoke ApplicationProvider.getApplicationContext() in local unit test.

### Expected Results
Work well, no exception thrown.

### Actual Results
The exception "java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation." is thrown.

### AndroidX Test and Android OS Versions
v1.2.0

**Comment by yongce** [comment]
It's my mistake. I invoked ApplicationProvider.getApplicationContext() in @BeforeClass method.

**Comment by tomeeeS** [comment]
The docs should mention invoking it in @BeforeClass is a problem, because that's an obvious place to put it.
I concluded Robolectric was just not working in local unit tests and spent hours refactoring.

**Comment by kaarthickmlsg** [comment]
I invoked ApplicationProvider.getApplicationContext() in @Before class but I still get the same error. How do we solve this?

**Comment by swapnilgt** [comment]
@kaarthickmlsg Even this didn't work for me. Anyone else got his working.

**Comment by yongce** [comment]
> @kaarthickmlsg Even this didn't work for me. Anyone else got his working?

Use @RunWith(AndroidJUnit4.class) or @RunWith(RobolectricTestRunner.class)

**Comment by TWiStErRob** [comment]
If using with [`@RunWith`](https://github.com/android/android-test/issues/409#issuecomment-770521310) and inside [`@Before`](https://github.com/android/android-test/issues/409#issuecomment-552876208) or `@Test` doesn't work I highly recommend creating a repro project based on the principles outlined here: http://sscce.org/.

**Comment by polly3d** [comment]
> If using with [`@RunWith`](https://github.com/android/android-test/issues/409#issuecomment-770521310) and inside [`@Before`](https://github.com/android/android-test/issues/409#issuecomment-552876208) or `@Test` doesn't work I highly recommend creating a repro project based on the principles outlined here: http://sscce.org/ and opening a new issue.

I have the same issue. `@RunWith` doesn't solve this problem.

**Comment by viveksomaiya1103** [comment]
Any anyone found the solution?

**Comment by sk8geek** [comment]
Having the same issue, extensive searching led me here.  Android developer documentation has nothing that helps. Very frustrating.

**Comment by KenM66** [comment]
I'm having this problem myself too.  Nothing I've found online has worked yet.

**Comment by AndreasBBS** [comment]
I just lost a lifetime over this. Make sure you're not using jupiter @Test or anything from jupiter. It has to be Juni4 @Test and stuff.

**Comment by ronenfe** [comment]
I get this error when trying to start a service. I don't even use any tests:

class MainActivity : AppCompatActivity() {
    private val mLastLocation: Location? = null

    // android.app.Activity
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setPermissions()
        startService(Intent(this, HistoriaService::class.java))
        supportFragmentManager
            .beginTransaction()
            .replace(android.R.id.content, Preferences())
            .commit()
    }

 ```
  class HistoriaService : Service() {
    override fun onBind(intent: Intent?): IBinder? {
        return null
    }

    // android.app.Service
    override fun onCreate() {
        super.onCreate()
        **getApplicationContext<Context>()**.contentResolver
            .registerContentObserver(
                CallLog.Calls.CONTENT_URI,
                true,
                CallLogContentObserver(Handler(), ApplicationProvider.getApplicationContext())
            )
    }

    // android.app.Service
    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        super.onStartCommand(intent, flags, startId)
        return START_STICKY
    }

}

```

**Comment by TWiStErRob** [comment]
@ronenfe You've correctly identified the problem being `getApplicationContext<Context>()`.

The solution is to remove the generics from the method call: `getApplicationContext()`
(this will call `Context#getApplicationContext()`, note: `Service extends Context`)

Then review your dependencies: the `ApplicationProvider` class should not be visible/bundled in production code, it's meant for Robolectric/Espresso/Instrumentation tests only.

**Comment by ronenfe** [comment]
I changed it to this, but still have the same problem. It fails in the service, not in a test? I don't use tests. I  only left the example tests that are put automatically when creating a new project:
```
    override fun onCreate() {
        super.onCreate()
        getApplicationContext().contentResolver
```

**Comment by ronenfe** [comment]
Ok I replaced getApplicationContext().contentResolver with this and it worked.
Also replaced ApplicationProvider.getApplicationContext() with this.
I still not sure about the consequences of this and if my program will still be able to work but I don't have exceptions now.
