### ISSUE TITLE
Fragment arguments are lost when launched using launchFragmentInContainer() with a factory

### ISSUE THREAD

**Issue by manabreak** [android/android-test#442]
### Description
When trying to test a fragment and using `launchFragmentInContainer()` to create the fragment with a factory, the arguments are lost. A sample code would like this:
```
// Fragment class to test
class MyFragment: Fragment {
    companion object {
        fun newInstance(foo: String): MyFragment {
            val bundle = Bundle()
            bundle.putString("FOO", foo)
            val frag = MyFragment()
            frag.setArguments(bundle)
            return frag
        }
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        // This will be null
        val foo = arguments!!.getString("FOO")
    }
}

// Test code
@Test
fun testFragment() {
    launchFragmentInContainer(null, R.style.AppTheme, {
        MyFragment.newInstance("BAR")
    })
}
```

### Steps to Reproduce
1. Create a fragment with a fragment factory and pass arguments
2. Try to use the arguments inside the fragment

### Expected Results
Arguments are delivered and can be used.

### Actual Results
Arguments are missing.

### AndroidX Test and Android OS Versions
```
androidx.fragment:fragment-testing:1.1.0
androidx.test:runner:1.2.0
androidx.test:rules:1.2.0
androidx.test.ext:junit:1.1.1
androidx.test:orchestrator:1.2.0
```

**Comment by manabreak** [comment]
It seems that the fragment's arguments are always overridden by the arguments that are passed to the `launchFragmentInContainer` method:

```
@Override
public void perform(EmptyFragmentActivity activity) {
    if (factory != null) {
        ViewModelProvider viewModelProvider = new ViewModelProvider(
                activity,
                ViewModelProvider.AndroidViewModelFactory.getInstance(
                        activity.getApplication()));
        viewModelProvider
                .get(FragmentFactoryHolderViewModel.class)
                .setFragmentFactory(factory);
        activity.getSupportFragmentManager().setFragmentFactory(factory);
    }
    Fragment fragment = activity.getSupportFragmentManager()
            .getFragmentFactory().instantiate(
                    Preconditions.checkNotNull(fragmentClass.getClassLoader()),
                    fragmentClass.getName());
    fragment.setArguments(fragmentArgs);
    activity.getSupportFragmentManager()
            .beginTransaction()
            .add(containerViewId, fragment, FRAGMENT_TAG)
            .commitNow();
}
```

I'd propose to either check whether or not the fragment already has the arguments bundle set, or alternatively, provide an overload for `launchFragmentInContainer` that does not take the arguments bundle as a parameter.

**Comment by yuuki3655** [comment]
I forwarded this issue to Fragment team and confirmed that this is the intended behavior:
https://issuetracker.google.com/issues/141877044

> FragmentScenario is consistent with how FragmentManager itself uses the FragmentFactory - explicitly calling setArguments() after instantiation and this is therefore working as intended.
