### ISSUE TITLE
Unable to build using bazel 3.1.0

### ISSUE THREAD

**Issue by darran-kelinske-fivestars** [android/android-test#626]
### Description

Thank you for your work on this these testing frameworks and thank you for making it publicly available.

I am unable to build a fresh checkout of this project on master.

### Steps to Reproduce

Download repository and follow steps in the contributing doc

### Expected Results

The project builds successfully

### Actual Results

Build fails with:

daz@daz:/rom/aosp-mirror/android-test$ bazel build :axt_m2repository
ERROR: /home/daz/.cache/bazel/_bazel_daz/ff62db25b941d7730a4c94ee1d6f2c41/external/robolectric/bazel/robolectric.bzl:2:5: Traceback (most recent call last):
        File "/rom/aosp-mirror/android-test/WORKSPACE", line 130
                robolectric_repositories()
        File "/home/daz/.cache/bazel/_bazel_daz/ff62db25b941d7730a4c94ee1d6f2c41/external/robolectric/bazel/robolectric.bzl", line 381, in robolectric_repositories
                android_all_jars()
        File "/home/daz/.cache/bazel/_bazel_daz/ff62db25b941d7730a4c94ee1d6f2c41/external/robolectric/bazel/robolectric.bzl", line 2, in android_all_jars
                native.maven_jar
no native function or rule 'maven_jar'
Available attributes: aar_import, action_listener, alias, android_binary, android_device, android_device_script_fixture, android_host_service_fixture, android_instrumentation_test, android_library, android_local_test, android_ndk_repository, android_sdk, android_sdk_repository, android_tools_defaults_jar, apple_binary, apple_cc_toolchain, apple_static_library, available_xcodes, bazel_version, bind, cc_binary, cc_host_toolchain_alias, cc_import, cc_libc_top_alias, cc_library, cc_proto_library, cc_test, cc_toolchain, cc_toolchain_alias, cc_toolchain_suite, config_feature_flag, config_setting, constraint_setting, constraint_value, environment, existing_rule, existing_rules, exports_files, extra_action, fdo_prefetch_hints, fdo_profile, filegroup, genquery, genrule, glob, j2objc_library, java_binary, java_import, java_library, java_lite_proto_library, java_package_configuration, java_plugin, java_proto_library, java_runtime, java_runtime_alias, java_test, java_toolchain, java_toolchain_alias, label_flag, label_setting, local_config_platform, local_repository, new_local_repository, ninja_build, ninja_graph, objc_import, objc_library, package_group, package_name, platform, proto_lang_toolchain, proto_library, py_binary, py_library, py_runtime, py_test, register_execution_platforms, register_toolchains, repository_name, sh_binary, sh_library, sh_test, test_suite, toolchain, toolchain_type, xcode_config, xcode_config_alias, xcode_version
ERROR: error loading package '': Encountered error while reading extension file 'kotlin/kotlin.bzl': no such package '@io_bazel_rules_kotlin//kotlin': error loading package 'external': Could not load //external package
INFO: Elapsed time: 0.061s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

### AndroidX Test and Android OS Versions

master branch

### Link to a public git repo demonstrating the problem:

the master branch of this repository

**Comment by darran-kelinske-fivestars** [comment]
WORKAROUND

Build branch:

`androidx-test-1.3.0-beta01`

Use bazel-2.2.0

`bazel-2.2.0 build :axt_m2repository`

**Comment by hoisie** [comment]
Thanks for reporting this issue. bazel 3.1 seems to have been released fairly recently and we haven't had a chance to support it yet. There seem to be a few other issues related to bazel 3.1 (I'm having issues with proguard). In the meantime I would recommend sticking with bazel 2.2 if possible.

**Comment by hoisie** [comment]
Can you try again with the latest master? https://github.com/android/android-test/pull/633 should fix it.

**Comment by darran-kelinske-fivestars** [comment]
yes - thank you
