### ISSUE TITLE
Using Espresso in a local JVM test?

### ISSUE THREAD

**Issue by eightx2** [android/android-test#636]
I've been writing instrumented tests using Espresso for quite a few years now, and that's why I was quite baffled when I saw this:

https://github.com/android/testing-samples/tree/master/ui/espresso/BasicSample

In this example repo, there's a [local test file](https://github.com/android/testing-samples/blob/master/ui/espresso/BasicSample/app/src/test/java/com/example/android/testing/espresso/BasicSample/ChangeTextBehaviorLocalTest.java) that runs some local JUnit tests on the JVM.
We all know that JVM tests are to be used when you don't need any UI or any specific Android framework component (without mocking it), and this is the first time I have ever noticed any usage of Espresso in the `test` folder of an Android project. All documentation I have ever come across in the Android testing documentation pages state that UI tests only should "live" in `androidTest`, which makes complete sense to me.

Can someone please explain why one would want to write Espresso-based tests that run locally?

**Comment by TarCV** [comment]
I guess it has something to do with Robolectric (Android emulation for JVM). I remember Google told about improving UI testing with it in one of keynotes.
Although, I'm not sure if there are tutorials by Google on that.

**Comment by hoisie** [comment]
Tests that run locally (that is using Robolectric on the JVM) are much faster and less flaky than tests that run in emulators and devices. This tends to work well on continuous integration platforms. More info on Espresso APIs in Robolectric: http://robolectric.org/androidx_test/.

**Comment by hoisie** [comment]
Closing this issue for now as there does not seem to be an actionable issue here.
