### ISSUE TITLE
Android Test Orchestrator throwing ClassNotFoundException Invalid name for parameterized tests

### ISSUE THREAD

**Issue by adil-hussain-84** [android/android-test#975]
### Description

In an instrumentation test class which is to run as a [Parameterized](https://junit.org/junit4/javadoc/4.12/org/junit/runners/Parameterized.html) test, if any of the parameters is an enum value and `{0}`, `{1}` etc is used in the [Parameterized.Parameters.name](https://junit.org/junit4/javadoc/4.13/org/junit/runners/Parameterized.Parameters.html#name) pattern, then Android Test Orchestrator fails to run the parameterized test and throws a [ClassNotFoundException](https://docs.oracle.com/javase/7/docs/api/java/lang/ClassNotFoundException.html) with a message of `"Invalid name"`.

### Steps to Reproduce

1. Define a parameterized test class in the `androidTest` folder of an Android project.
2. Ensure that one of the parameters is an enum value.
3. Set the [Parameterized.Parameters.name](https://junit.org/junit4/javadoc/4.13/org/junit/runners/Parameterized.Parameters.html#name) value (which is passed into the [Parameterized.Parameters](https://junit.org/junit4/javadoc/4.13/org/junit/runners/Parameterized.Parameters.html) annotation) to `"{0}"`.
4. Add `testOptions.execution 'ANDROIDX_TEST_ORCHESTRATOR'` to the Android project's `build.gradle` file so that the instrumentation tests run with Android Test Orchestrator.
5. Run the test class.

### Expected Results

The parameterized tests runs fine.

### Actual Results

The parameterized tests throw [ClassNotFoundException](https://docs.oracle.com/javase/7/docs/api/java/lang/ClassNotFoundException.html) with a message of `"Invalid name"`.

### AndroidX Test and Android OS Versions

```
androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'
androidTestImplementation 'androidx.test.ext:junit:1.1.2'
androidTestUtil 'androidx.test:orchestrator:1.3.0'
```

Attempted with an Android 5.1, Android 10.0 and Android 11.0 emulator. All exhibit the same behaviour.

### Link to a public git repo demonstrating the problem:

- [https://github.com/adil-hussain-84/android-test-experiments/tree/master/app1](https://github.com/adil-hussain-84/android-test-experiments/tree/master/app1)

See the [BadParameterizedTest.kt](https://github.com/adil-hussain-84/android-test-experiments/blob/master/app1/src/androidTest/java/androidx/test/experiments/app/BadParameterizedTest.kt), [GoodParameterizedTest.kt](https://github.com/adil-hussain-84/android-test-experiments/blob/master/app1/src/androidTest/java/androidx/test/experiments/app/GoodParameterizedTest.kt) and [build.gradle](https://github.com/adil-hussain-84/android-test-experiments/blob/master/app1/build.gradle) files in particular.

**Comment by adil-hussain-84** [comment]
I tried with the latest versions of the test libraries (as below) but experienced the same error.

### AndroidX Test and Android OS Versions

```
androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0-beta01'
androidTestImplementation 'androidx.test.ext:junit:1.1.3-beta01'
androidTestUtil 'androidx.test:orchestrator:1.4.0-beta01'
```

Attempted with an Android 5.1, Android 10.0 and Android 11.0 emulator. All exhibit the same behaviour.

**Comment by TWiStErRob** [comment]
#956

**Comment by adil-hussain-84** [comment]
Version `3.5.0` of the `androidx.test.espresso:espresso-core` library fixes the problem described in this issue.

I have updated https://github.com/adil-hussain-84/android-test-experiments/tree/master/app1 so it now demonstrates the fix rather than the problem.
